# CI de disparo manual

#nome da pipeline
name: Execução Manual

# gatilhos / triggers - regras de disparo
# gatilho manual = workflow_dispatch

on:
  workflow_dispatch:

#tarefas dentro da pipeline = jobs

jobs:
  #nome do job
  test:
  #maquina onde o job vai rodar
    runs-on: ubuntu-latest

    #passos do job
    steps:
      #clone do projeto
      - name: Checkout do código
        uses: actions/checkout@v4

      #instalação do Node.js
      - name: Instalação do Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      #instalação de dependências
      - name: Instalação de dependências
        run: npm install

      - name: Correção de vulnerabilidades do npm
        run: npm audit fix --force  

      #execução dos testes
      - name: Execução de testes via Mocha
        run: npm test